search_and_play:
  name: Search and Play
  description: Search for a podcast by term and play its latest episode on a media player
  target:
    entity:
      integration: media_player
  fields:
    entity_id:
      name: Media Player
      description: The media player entity to play the episode on
      selector:
        entity:
          domain: media_player
      required: true
    search_term:
      name: Search Term
      description: The search term to find the podcast
      selector:
        text:
      required: true 