search_and_play:
  name: Search and Play
  description: Search for a podcast by term and play its latest episode on a media player
  target:
    entity:
      integration: media_player
  fields:
    entity_id:
      name: Media Player
      description: The media player entity to play the episode on
      selector:
        entity:
          domain: media_player
      required: true
    search_term:
      name: Search Term
      description: The search term to find the podcast
      selector:
        text:
      required: true
    volume:
      name: Volume
      description: Optional volume level (0-100) to set before playing
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
      required: false

add_search_term:
  name: Add Search Term
  description: Add a new podcast search term to a specific PodcastIndex integration entry
  fields:
    search_term:
      name: Search Term
      description: The new search term to add (e.g. 'tech news' or a podcast ID)
      selector:
        text:
      required: true
    entry_id:
      name: PodcastIndex Integration
      description: The specific PodcastIndex integration entry to add the search term to (required to specify which integration instance)
      selector:
        config_entry:
          integration: podcast_index
      required: true

remove_search_term:
  name: Remove Search Term
  description: Remove a podcast search term from a specific PodcastIndex integration entry
  fields:
    search_term:
      name: Search Term
      description: The search term to remove (must match exactly)
      selector:
        text:
      required: true
    entry_id:
      name: PodcastIndex Integration
      description: The specific PodcastIndex integration entry to remove the search term from (required to specify which integration instance)
      selector:
        config_entry:
          integration: podcast_index
      required: true 